flaskr/models.py
from . import db
import json
from collections import namedtuple
from json import JSONEncoder

class Restriction:
    def __init__(self, enable, id, ingredients, name):
        self.enable, self.id, self.ingredients, self.name = enable, id, ingredients, name


class Ingredient:
    def __init__(self, description, id, name):
        self.description, self.id, self.name = description, id, name


class RestrictionEncoder(JSONEncoder):
    def default(self, o):
        return o.__dict__


class User(db.Model):
    """Data model for 'produtos'"""

    __tablename__ = 'user'
    id = db.Column(db.Integer,
                   primary_key=True)
    username = db.Column(db.String,
                         index=False,
                         unique=True,
                         nullable=False)
    password = db.Column(db.String,
                         nullable=False)

    def __repr__(self):
        return '<User {}>'.format(self.name)

flaskr/__init__.py
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app(test_config=None):
    # WIN COMMANDS:
    # create and configure the app
    # $set FLASK_APP=flaskr
    # $set FLASK_ENV=development
    # $flask run
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        SQLALCHEMY_DATABASE_URI=os.path.join('sqlite:///'+app.instance_path, 'marple.sqlite'),
        SQLALCHEMY_TRACK_MODIFICATIONS=False
    )
    # ensure the instance folder exists
    try:
        os.makedirs('sqlite:///'+app.instance_path)
    except OSError:
        pass

    db.init_app(app)

    with app.app_context():
        from . import routes
        app.register_blueprint(routes.bp)

        from . import auth
        app.register_blueprint(auth.bp)

        db.create_all()

    return app

flaskr/auth.py
import functools

from flask import (
 Blueprint, flash, g, redirect, render_template, request, session, url_for
)

from werkzeug.security import check_password_hash, generate_password_hash

from .models import db, User


# This creates a Blueprint named 'auth'
bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif User.query.filter(User.username == username).first() is not None:
            error = 'User {} is already registered.'.format(username)

        if error is None:
            new_user = User(username=username,
                            password=generate_password_hash(password))
            db.session.add(new_user)
            db.session.commit()

            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None
        user = User.query.filter(User.username == username).first()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user.password, password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('routes.index'))

        flash(error)

    return render_template('auth/login.html')


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.filter(User.id == user_id).first()


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('routes.index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

flaskr/routes.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for, make_response, current_app as app
)

from datetime import datetime as dt
from .models import db, User, Restriction, Ingredient, RestrictionEncoder
from flaskr.auth import login_required
from datetime import datetime
import pyrebase
import uuid
import json

config = {
    "apiKey": "AIzaSyAZbMMbdFR3zK8-giYMh1Dg5Q_pmgLrRMQ",
    "authDomain": "marple-3161a.firebaseapp.com",
    "databaseURL": "https://marple-3161a.firebaseio.com",
    "projectId": "marple-3161a",
    "storageBucket": "marple-3161a.appspot.com",
    "messagingSenderId": "348358607845",
    "appId": "1:348358607845:web:24063f823153fc00d5a50c",
    "measurementId": "G-4ZV65FBK7H"
}

firebase = pyrebase.initialize_app(config)
dbf = firebase.database();


bp = Blueprint('routes', __name__, url_prefix='/restrictions')


def load_restrictions():
    restrictions = dbf.child("Restriction").get()
    restriction_list = []
    for restriction_fb in restrictions.each():
        restriction_list.append(restriction_fb.val())

    return restriction_list


@bp.route('/')
@login_required
def index():
    restriction_list = load_restrictions()

    return render_template('restrictions/index.html', restrictions=restriction_list)


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    restrictions = dbf.child("Restriction").get()
    restriction_list = []
    for restriction_fb in restrictions.each():
        restriction_list.append(restriction_fb.val())

    if request.method == 'POST':
        name = request.form['name']
        ingredients = request.form['ingredients']
        error = None

        if not name or not ingredients:
            error = 'Name is required.'

        ingredients_list = []
        count = 0
        for ingredient_name in ingredients.split(", "):
            ingredients_list.append(Ingredient("", count, ingredient_name))
            count += 1

        if error is None:
            new_restriction = Restriction(enable=True,
                                  id=restriction_list.__len__(),
                                  ingredients=ingredients_list,
                                  name=name)

            json_obj = json.dumps(new_restriction, cls=RestrictionEncoder)
            print(json.loads(json_obj))
            dbf.child("Restriction").child(name).set(json.loads(json_obj))

            return redirect(url_for('routes.index'))

        flash(error)

    return render_template('restrictions/create.html')


def get_product(id):
    product = Product.query.filter(Product.id == id).first()

    if product is None:
        abort(404, "Product id {0} doesn't exist.".format(id))

    return product


@bp.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    return redirect(url_for('routes.index'))


@bp.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update(id):
    return render_template('restrictions/update.html', product=product)

flaskr/templates/base.html
<!doctype html>
<title>Flaskr</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <h1>Exercício 3</h1>
  <ul>
      <li><a href="{{ url_for('routes.index') }}">lista</a>
    {% if g.user %}
      <li><span>{{ g.user['username'] }}</span>
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

flaskr/templates/restrictions/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Novo Produto{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="name">Nome</label>
    <input name="name" id="name" value="{{ request.form['name'] }}" required>
    <label for="ingredients">Ingredientes</label>
    <textarea name="ingredients" id="ingredients" value="{{ request.form['ingredients'] }}" required></textarea>

    <input type="submit" value="Save">
  </form>
{% endblock %}

flaskr/templates/restrictions/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Compras{% endblock %}</h1>
    {% if g.user %}
        <a class="action" href="{{ url_for('routes.create') }}">Novo</a>
    {% endif %}
{% endblock %}

{% block content %}
    {% if g.user %}
      {% for restriction in restrictions %}
        <product class="restriction">
          <header>
            <div>
              <h1>{{ restriction['name'] }}</h1>
              <div class="about">
                  Ingredientes:
                  {% for ingredient in restriction['ingredients'] %}
                    {{ ingredient['name'] }},
                  {% endfor %}
              </div>
            </div>
            <a class="action" href="{{ url_for('routes.update', id=restriction['id']) }}">Editar</a>
          </header>
        </product>
        {% if not loop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    {% endif %}
{% endblock %}

flaskr/templates/restrictions/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ product['name'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
  </form>
  <hr>
{% endblock %}